# Generated by Django 6.1.1 on 2026-10-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='duracao_minutos',
            field=models.IntegerField(help_text='Duração em minutos (ex: 180 para 3h)'),
        ),
    ]
