# Generated by Django 6.1.1 on 2026-10-07 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_alter_servico_duracao_minutos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agendamentos.servico'),
        ),
    ]
